### ISSUE TITLE
Report: Memory Vendor is alphanumeric string

### ISSUE THREAD

**Issue by zjassiem** [ska-sa/katsdpnetboxutilities#11]
Certain memory vendors print as alphanumeric strings instead of something that is human-readable.

vendor : 00AD00B300AD in the CAL machines 
and 
vendor: 002C00B3002C in the ING machines

**Comment by stix121** [comment]
Using Lab 1 as an example, the output is "vendor": "00CE04B300CE".

![CleanShot 2021-01-18 at 18 49 50](https://user-images.githubusercontent.com/2537257/104943238-1a031500-59be-11eb-98dc-80f8298d3b2f.jpg)

**Comment by zjassiem** [comment]
My issue was more along the lines of resolving the "00CE04B300CE" into "Samsung" as it appears that this particular DIMM manufacturer is Samsung when searching online for the product number "M393B2G70QH0-YK0".

**Comment by martinslabber** [comment]
I am closing this issue.
It is a valid request to display the vendor's common name, but unfortunately, this is not provided by the device when we query it.
We had a look to see if the system provides this information directly and it does not, without doing searches and more string processing and mangling than whats sensable. Thus out of scope.

You can re-open this if your willing to provide and maintain a lookup table. Note vendors do change and buy sections of one another companies, so such a lookup table will have to be a living document.

Thanks for the ticket, but as you mentioned an internet search can provide the necessary information.

**Comment by zjassiem** [comment]
FYI
for future reference
@KgomotsoMonnakgotla
