### ISSUE TITLE
host report: Memory size as human readable not as bytes

### ISSUE THREAD

**Issue by martinslabber** [ska-sa/katsdpnetboxutilities#7]
Use [boltons.strutils.bytes2human](https://boltons.readthedocs.io/en/latest/strutils.html#boltons.strutils.bytes2human)(size, ndigits=2) to create a better size value for memory.

**Comment by stix121** [comment]
http://sdp-services.sdp.kat.ac.za/servers/lab1/lab1.pdf

**Comment by stix121** [comment]
http://sdp-services.sdp.kat.ac.za/servers/lab1/lab1.pdf
